export const categoriasGastos = [
  { id: 1, nombre: "Alimentación", total: "120,500" },
  { id: 2, nombre: "Vivienda", total: "800,000" },
  { id: 3, nombre: "Transporte", total: "150,300" },
  { id: 4, nombre: "Salud", total: "250,800" },
  { id: 5, nombre: "Educación", total: "135,600" },
  { id: 6, nombre: "Entretenimiento", total: "220,400" },
  { id: 7, nombre: "Ropa y accesorios", total: "110,750" },
  { id: 8, nombre: "Tecnología", total: "650,900" },
  { id: 9, nombre: "Finanzas", total: "190,200" },
  { id: 10, nombre: "Otros", total: "95,900" },
  { id: 11, nombre: "Hogar", total: "260,300" },
  { id: 12, nombre: "Familia", total: "140,000" },
  { id: 13, nombre: "Mascotas", total: "180,450" },
  { id: 14, nombre: "Regalos y Donaciones", total: "160,600" },
  { id: 15, nombre: "Viajes", total: "500,500" },
  { id: 16, nombre: "Ahorros e Inversiones", total: "2,000,000" },
  { id: 17, nombre: "Hobbies", total: "180,800" },
  { id: 18, nombre: "Servicios Públicos", total: "130,250" },
  { id: 19, nombre: "Cuidado Personal", total: "165,300" },
  { id: 20, nombre: "Eventos Sociales", total: "120,900" },
  { id: 21, nombre: "Mascotas", total: "180,450" },
  { id: 22, nombre: "Regalos y Donaciones", total: "160,600" },
  { id: 23, nombre: "Viajes", total: "500,500" },
  { id: 24, nombre: "Ahorros e Inversiones", total: "2,000,000" },
  { id: 25, nombre: "Hobbies", total: "180,800" },
  { id: 26, nombre: "Servicios Públicos", total: "130,250" },
  { id: 27, nombre: "Cuidado Personal", total: "165,300" },
  { id: 28, nombre: "Eventos Sociales", total: "120,900" },
];

export const expenses = [
  {
    id: 1,
    amount: "45,230.50",
    category: "Alimentación",
    description: "Compra de supermercado",
    date: "2 De octubre 2024",
  },
  {
    id: 2,
    amount: "120,500.00",
    category: "Transporte",
    description: "Mantenimiento del automóvil",
    date: "15 De octubre 2024",
  },
  {
    id: 3,
    amount: "3,250.00",
    category: "Entretenimiento",
    description: "Cine con amigos",
    date: "20 De octubre 2024",
  },
  {
    id: 4,
    amount: "15,000.75",
    category: "Salud",
    description: "Consulta médica",
    date: "10 De octubre 2024",
  },
  {
    id: 5,
    amount: "8,900.25",
    category: "Ropa",
    description: "Compra de ropa de temporada",
    date: "12 De octubre 2024",
  },
  {
    id: 6,
    amount: "500.00",
    category: "Gastos varios",
    description: "Regalo de cumpleaños",
    date: "22 De octubre 2024",
  },
  {
    id: 7,
    amount: "22,450.90",
    category: "Educación",
    description: "Curso online de programación",
    date: "1 De octubre 2024",
  },
  {
    id: 8,
    amount: "6,300.00",
    category: "Hogar",
    description: "Reparación de electrodoméstico",
    date: "5 De octubre 2024",
  },
  {
    id: 9,
    amount: "35,780.00",
    category: "Viajes",
    description: "Viaje de fin de semana",
    date: "8 De octubre 2024",
  },
  {
    id: 10,
    amount: "1,200.99",
    category: "Mascotas",
    description: "Compra de alimentos para mascotas",
    date: "25 De octubre 2024",
  },
  {
    id: 11,
    amount: "2,750.00",
    category: "Servicios públicos",
    description: "Factura mensual de electricidad",
    date: "18 De octubre 2024",
  },
  {
    id: 12,
    amount: "1,500.50",
    category: "Entretenimiento",
    description: "Entradas para un concierto",
    date: "3 De octubre 2024",
  },
  {
    id: 13,
    amount: "900.00",
    category: "Alimentación",
    description: "Cena en un restaurante",
    date: "14 De octubre 2024",
  },
  {
    id: 14,
    amount: "5,200.00",
    category: "Transporte",
    description: "Pase de transporte público",
    date: "17 De octubre 2024",
  },
  {
    id: 15,
    amount: "4,500.75",
    category: "Salud",
    description: "Medicamentos recetados",
    date: "30 De septiembre 2024",
  },
  {
    id: 16,
    amount: "2,000.00",
    category: "Ropa",
    description: "Compra de zapatos",
    date: "6 De octubre 2024",
  },
  {
    id: 17,
    amount: "1,800.00",
    category: "Hogar",
    description: "Productos de limpieza para el hogar",
    date: "4 De octubre 2024",
  },
  {
    id: 18,
    amount: "7,000.00",
    category: "Viajes",
    description: "Billetes de avión",
    date: "9 De octubre 2024",
  },
  {
    id: 19,
    amount: "1,100.99",
    category: "Mascotas",
    description: "Visita al veterinario",
    date: "21 De octubre 2024",
  },
  {
    id: 20,
    amount: "3,500.00",
    category: "Servicios públicos",
    description: "Factura de agua",
    date: "19 De octubre 2024",
  },
  {
    id: 21,
    amount: "2,200.50",
    category: "Gastos varios",
    description: "Servicio de suscripción",
    date: "23 De octubre 2024",
  },
];

export const expensesGraph = [
  {
    id: 1,
    amount: 45230.50,
    category: "Alimentación",
    description: "Compra de supermercado",
    date: "2 De octubre 2024",
  },
  {
    id: 2,
    amount: 120500.00,
    category: "Transporte",
    description: "Mantenimiento del automóvil",
    date: "15 De octubre 2024",
  },
  {
    id: 3,
    amount: 3250.00,
    category: "Entretenimiento",
    description: "Cine con amigos",
    date: "20 De octubre 2024",
  },
  {
    id: 4,
    amount: 15000.75,
    category: "Salud",
    description: "Consulta médica",
    date: "10 De octubre 2024",
  },
  {
    id: 5,
    amount: 8900.25,
    category: "Ropa",
    description: "Compra de ropa de temporada",
    date: "12 De octubre 2024",
  },
  {
    id: 6,
    amount: 500.00,
    category: "Gastos varios",
    description: "Regalo de cumpleaños",
    date: "22 De octubre 2024",
  },
  {
    id: 7,
    amount: 22450.90,
    category: "Educación",
    description: "Curso online de programación",
    date: "1 De octubre 2024",
  },
  {
    id: 8,
    amount: 6300.00,
    category: "Hogar",
    description: "Reparación de electrodoméstico",
    date: "5 De octubre 2024",
  },
  {
    id: 9,
    amount: 35780.00,
    category: "Viajes",
    description: "Viaje de fin de semana",
    date: "8 De octubre 2024",
  },
  {
    id: 10,
    amount: 1200.99,
    category: "Mascotas",
    description: "Compra de alimentos para mascotas",
    date: "25 De octubre 2024",
  },
  {
    id: 11,
    amount: 2750.00,
    category: "Servicios públicos",
    description: "Factura mensual de electricidad",
    date: "18 De octubre 2024",
  },
  {
    id: 12,
    amount: 1500.50,
    category: "Entretenimiento",
    description: "Entradas para un concierto",
    date: "3 De octubre 2024",
  },
  {
    id: 13,
    amount: 900.00,
    category: "Alimentación",
    description: "Cena en un restaurante",
    date: "14 De octubre 2024",
  },
  {
    id: 14,
    amount: 5200.00,
    category: "Transporte",
    description: "Pase de transporte público",
    date: "17 De octubre 2024",
  },
  {
    id: 15,
    amount: 4500.75,
    category: "Salud",
    description: "Medicamentos recetados",
    date: "30 De septiembre 2024",
  },
  {
    id: 16,
    amount: 2000.00,
    category: "Ropa",
    description: "Compra de zapatos",
    date: "6 De octubre 2024",
  },
  {
    id: 17,
    amount: 1800.00,
    category: "Hogar",
    description: "Productos de limpieza para el hogar",
    date: "4 De octubre 2024",
  },
  {
    id: 18,
    amount: 7000.00,
    category: "Viajes",
    description: "Billetes de avión",
    date: "9 De octubre 2024",
  },
  {
    id: 19,
    amount: 1100.99,
    category: "Mascotas",
    description: "Visita al veterinario",
    date: "21 De octubre 2024",
  },
  {
    id: 20,
    amount: 3500.00,
    category: "Servicios públicos",
    description: "Factura de agua",
    date: "19 De octubre 2024",
  },
  {
    id: 21,
    amount: 2200.50,
    category: "Gastos varios",
    description: "Servicio de suscripción",
    date: "23 De octubre 2024",
  },
];



